# Generated by Django 4.0.3 on 2022-04-11 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_category_alter_book_photo_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(max_length=4, verbose_name='Издана в')),
            ],
            options={
                'verbose_name': 'Год издания',
                'verbose_name_plural': 'Год издания',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='women.year'),
        ),
    ]
